### ISSUE TITLE
Issue with Pin Configuration on ESP32-C6-Dev-Kit-N8

### ISSUE THREAD

**Issue by rmarcoro** [pervu/DWIN2_Display#1]
Dear Pavel,

First of all, I would like to thank you for your excellent work on the DWIN2_Display library. It has been incredibly useful, and I appreciate the effort you’ve put into developing it.

I’m currently working with the ESP32-C6-Dev-Kit-N8, and I encountered an issue related to pin configuration in the Dwin2.h file. Specifically, at line 173:

https://github.com/pervu/DWIN2_Display/blob/b2547b304d0057dfaa8e055baf25f8087287083e/Dwin2.h#L173

On this specific ESP32 board, the RX and TX pins need to be swapped due to their directional configuration. For users of this board, it is necessary to change the parameters after installing the library to:
rxPin = 17
txPin = 16

I thought it might be helpful to report this, as others using the same board might face the same issue.

Once again, thank you for your amazing work and support!

Best regards,
Salgueiro

**Comment by pervu** [comment]
Hello, Salgueiro! Thanks for the feedback.

You don't need to change header file, you can init DWIN2 object on your needs with .begin() method with arguments:
```cpp
DWIN2 dwc;
dwc.begin(0xFFFF, 0x1000, 17, 16);
```

Best regards, Pavel P.
